swagger: "2.0"
info:
  description: API of the xMeme application is documented here
  version: "1.0.0"
  title: Swagger for xMeme
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /memes:
    get:
      operationId: backend.memes.read_all
      tags:
        - Memes
      summary: Read the 100 latest memes
      description: Read the 100 latest memes
      responses:
        200:
          description: Successfully read the 100 latest memes
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of the meme
                name:
                  type: string
                  description: Name of the meme owner
                caption:
                  type: string
                  description: Caption of the meme
                url:
                  type: string
                  description: Url of the meme image

    post:
      operationId: backend.memes.create
      tags:
        - Memes
      summary: Create a new meme
      description: Create a new meme
      parameters:
        - name: meme
          in: body
          description: Meme to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the meme owner
              caption:
                type: string
                description: Caption of the meme to create
              url:
                type: string
                description: Url of the meme to create
      responses:
        201:
          description: Successfully created meme
          schema:
            properties:
              id:
                type: integer
                description: Id of the meme

  /memes/{id}:
    get:
      operationId: backend.memes.read_one
      tags:
        - Memes
      summary: Read a meme
      description: Read a meme
      parameters:
        - name: id
          in: path
          description: Id of the meme to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read meme from the memes data operation
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the meme
              name:
                type: string
                description: Name of the meme owner
              caption:
                type: string
                description: Caption of the meme
              url:
                type: string
                description: Url of the meme image

    patch:
      operationId: backend.memes.update
      tags:
        - Memes
      summary: Update a meme's caption, url or both
      description: Update a meme's caption, url or both
      parameters:
        - name: id
          in: path
          description: Id the meme to update
          type: integer
          required: True
        - name: meme
          in: body
          schema:
            type: object
            properties:
              caption:
                type: string
                description: Caption of the meme
              url:
                type: string
                description: Url of the meme image
      responses:
        200:
          description: Successfully updated the meme
          schema:
            properties:
              id:
                type: integer
                description: Id of the meme in the database
              name:
                type: string
                description: Name of the meme owner
              caption:
                type: string
                description: Caption of the meme
              url:
                type: string
                description: Url of the meme image